# Generated by Django 5.0 on 2024-04-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=200)),
                ('aboutMe', models.CharField(max_length=500)),
                ('certifications', models.CharField(max_length=1000)),
            ],
        ),
    ]
